-- luacheck configuration for the Mangosbot WoW addon.

std = "lua51"

-- Addon globals shared across files (defined, mutated, or cross-referenced).
globals = {
	-- Core
	"__genOrderedIndex",
	"AfterPrefix",
	"botCount",
	"botTable",
	"ClassToken",
	"CommandSeparator",
	"DropDownMenu",
	"EnsureAddonPrefix",
	"fmod",
	"GetChatEventPayload",
	"GetMangosbotClient",
	"GetMangosbotVersion",
	"MB_HasDeathKnight",
	"MB_Invite",
	"NormalizeMessage",
	"OnKeyBindingDown",
	"OnSystemMessage",
	"OnWhisper",
	"orderedNext",
	"orderedPairs",
	"partyName",
	"partySize",
	"splitString2",
	"StartsWith",
	"StripColors",
	"tablelength",
	"trim2",
	"wait",
	-- Protocol
	"CombineBotCommands",
	"InstallBotChatFilters",
	"IsBotProtocolMessage",
	"QueryBotParty",
	"QuerySelectedBot",
	"SendBotAddonCommand",
	"SendBotCommand",
	-- Commands / UI
	"BotDebugCopyFrame",
	"BotDebugLogMessage",
	"BotDebugPanel",
	"BotMenuChatTable",
	"BotMenuItems",
	"BotRoster",
	"ClearBotDebugLog",
	"ClickGroupToolBarButton",
	"ClickToolBarButton",
	"CreateBotDebugPanel",
	"CreateBotRoster",
	"createDropdown",
	"CreateDropDownMenu",
	"CreateFormationToolBar",
	"CreateGenericCombatToolBar",
	"CreateGenericNonCombatToolBar",
	"CreateMovementToolBar",
	"CreateRtiCcToolBar",
	"CreateRtiToolBar",
	"CreateSaveManaToolBar",
	"CreateSelectedBotPanel",
	"CreateStanceToolBar",
	"CreateToolBar",
	"CurrentBot",
	"EnablePositionSaving",
	"frameopts",
	"GroupToolBars",
	"OpenDropDownMenu",
	"OpenDropDownMenuForCurrentBot",
	"ResizeBotPanel",
	"SelectedBotPanel",
	"SetFrameColor",
	"ShowBotDebugCopyFrame",
	"StartChat",
	"ToggleButton",
	"ToolBarButtonOnClick",
	"ToolBars",
	"UpdateBotDebugPanel",
	"UpdateGroupToolBar",
	-- Localization / slash commands
	"BINDING_HEADER_MANGOSBOT",
	"BINDING_NAME_ATTACK",
	"BINDING_NAME_BOOST",
	"BINDING_NAME_DEBUG",
	"BINDING_NAME_FLEE",
	"BINDING_NAME_FOLLOW",
	"BINDING_NAME_LOOT",
	"BINDING_NAME_PASSIVE",
	"BINDING_NAME_PULL",
	"BINDING_NAME_ROSTER",
	"BINDING_NAME_STAY",
	"SLASH_MANGOSBOT1",
	"SlashCmdList",
	-- Hooked / redefined stock globals
	"ChatFrame_MessageEventHandler",
	"print",
}

-- WoW client API and implicit event globals (read-only).
read_globals = {
	"arg1",
	"arg2",
	"arg3",
	"arg4",
	"arg5",
	"arg6",
	"arg7",
	"arg8",
	"arg9",
	"ChatFrame_AddMessageEventFilter",
	"CreateFrame",
	"date",
	"DEFAULT_CHAT_FRAME",
	"DoEmote",
	"event",
	"GameTooltip",
	"GetBuildInfo",
	"GetCursorPosition",
	"getglobal",
	"GetNumPartyMembers",
	"GetNumRaidMembers",
	"GetUnitName",
	"HideDropDownMenu",
	"InviteByName",
	"InviteUnit",
	"RAID_CLASS_COLORS",
	"SendAddonMessage",
	"SendChatMessage",
	"this",
	"tinsert",
	"ToggleDropDownMenu",
	"tremove",
	"UIDropDownMenu_AddButton",
	"UIDropDownMenu_Initialize",
	"UIParent",
	"UnitClass",
	"UnitExists",
	"UnitIsEnemy",
	"UnitIsPlayer",
	"UnitName",
	-- Lua 5.0 length helper (WoW 1.12); polyfilled in the test harness
	"table.getn",
	"table.concat",
}

-- Test harness stubs WoW APIs and may redefine std/read globals.
files["src/test.lua"] = {
	globals = {
		"CreateFrame",
		"DEFAULT_CHAT_FRAME",
		"frames",
		"GetBuildInfo",
		"GetNumPartyMembers",
		"GetNumRaidMembers",
		"InviteByName",
		"InviteUnit",
		"SendAddonMessage",
		"SendChatMessage",
		"table",
		"tinsert",
		"tremove",
		"UIParent",
		"UnitName",
		"unpack",
	},
}
